apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  type: LoadBalancer
  selector:
    app: url-shortener
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 5 #how many pod you want to run
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: alimertcan/url_shortener:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000